language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tokyotyrant
script:
  - ttserver -dmn
  - mvn test

